jobs:
  setup:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Test.
          command: gradle test
      - store_test_results:
          path: build/test-results
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle make jar.
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
  dockerize:
    machine: true
    steps:
      - checkout
      # login to docker
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
      # build image
      - run: docker build -t draagvah/ccitestapp:$CIRCLE_SHA1 .
      # deploy image
      - run: docker push draagvah/ccitestapp:$CIRCLE_SHA1
      - run: docker push draagvah/ccitestapp:latest

workflows:
  version: 2
  setup_test_build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - dockerize:
          requires:
            - build

