jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: 
          name: Run and build.
          command: |
            gradle test
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - store_test_results:
          path: build/test-results
